name: Build the markdown source files                                            
                                                                                 
on: push                                                                         
                                                                                 
jobs:                                                                            
  build:                                                                         
    runs-on: ubuntu-latest                                                       
    container: dalibo/pandocker                                                  
    steps:                                                                       
      - uses: actions/checkout@v3                                                
      - run: make
      - uses: actions/upload-artifact@v2
        with: 
          path: .
